Document: robin-hood-hashing
Title: Debian robin-hood-hashing Manual
Author: <insert document author here>
Abstract: This manual describes what robin-hood-hashing is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/robin-hood-hashing/robin-hood-hashing.sgml.gz

Format: postscript
Files: /usr/share/doc/robin-hood-hashing/robin-hood-hashing.ps.gz

Format: text
Files: /usr/share/doc/robin-hood-hashing/robin-hood-hashing.text.gz

Format: HTML
Index: /usr/share/doc/robin-hood-hashing/html/index.html
Files: /usr/share/doc/robin-hood-hashing/html/*.html
